gsap.from('.BGCircle1',  {delay: 1,x:-300, duration: 1, ease: 'expo.inOut', opacity:0})
gsap.from('.BGCircle2',  {delay: 1,x:300, duration: 1, ease: 'expo.inOut', opacity:0})
gsap.from('.BGCircle3',  {delay: 1, duration: 1, ease: 'expo.inOut', opacity:0})
gsap.from('.swiperbuttons',  {delay: 3,x:-100, duration: 3, ease: 'bounce.inOut', opacity:0})
gsap.from('.button',  {delay: 2,y:-50, duration: 1, ease: 'expo.inout', opacity:0})
gsap.from('.button1',  {delay: 2,y:-50, duration: 1, ease: 'expo.inout', opacity:0})
gsap.from('.socials',  {delay: 3,x:150,y:-100, duration: 1, ease: 'expo.inOut', opacity:0})
gsap.from('.button3',  {delay: 3,x:-300, y:100, duration: 1, ease: 'expo.inOut', opacity:0})